version: "3"
services:
    build_client: 
        context: ./client
        dockerfile: Dockerfile
        options: 
            - t
        args:
            - fantasticmemory:client
            - ./
    build_server:
        context: ./server
        dockerfile: Dockerfile 
        options: 
            - t
        args:
            - fantasticmemory:server
            - ./
    client:
    container_name: fantasticmemory:client
    restart: always
    build: .
    ports: 3000:3000
    links:
      - server
  server:
    container_name: fantasticmemory:server
    restart: always
    ports: 5000:5000
    links:
      - client
