version: "3.8"
services:
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
            args:
                - -t
                - fantasticmemory:client
                - ./
        container_name: fantasticmemory:client
        restart: always
        build: .
        ports: 
            - 3000:3000
        links:
            - server
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile 
            args:
                - -t
                - fantasticmemory:server
                - ./
        container_name: fantasticmemory:server
        restart: always
        ports: 
            - 5000:5000
