version: '3'

services:
  server-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: yarn start
  
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: yarn run dev
