version: '3'

services:

  server-prod:
    build:
      context: .
      dockerfile: prod-image.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    command: yarn start
  
  server-dev:
    build:
      context: .
      dockerfile: dev-image.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # you_local_path/:your_container_path/ which I bind to reflect changes to container
      - ./src:/app/src
    command: yarn dev
